import {getAltKeyStr} from "./get-device-key-strings";
import getCurrentLanguage from "./get-current-language";

const defaultShortcuts = {
  it: {
    "Muovi": '⇧ Shift + Q',
    "Punto": '⇧ Shift + W',
    "Segmento": '⇧ Shift + E',
    "Retta": '⇧ Shift + R',
    "Poligono": '⇧ Shift + T',
    "Circonferenza - centro e punto": '⇧ Shift + Y',
    "Seleziona oggetti": '⇧ Shift + U',
    "Mostra / Nascondi etichetta": '⇧ Shift + I',
    "Mostra / Nascondi oggetto": '⇧ Shift + O',
    "Elimina": '⇧ Shift + P',
    "Muovi la vista Grafici": '⇧ Shift + A',
    "Copia stile visuale": '⇧ Shift + S',
    "Punto medio o centro": '⇧ Shift + D',
    "Retta perpendicolare": '⇧ Shift + F',
    "Asse di un segmento": '⇧ Shift + G',
    "Retta parallela": '⇧ Shift + H',
    "Bisettrice": '⇧ Shift + J',
    "Tangenti": '⇧ Shift + K',
    "Luogo": '⇧ Shift + L',
    "Angolo": '⇧ Shift + Z',
    "Angolo di data misura": '⇧ Shift + X',
    "Distanza o lunghezza": '⇧ Shift + C',
    "Area": '⇧ Shift + V',
    "Slider": '⇧ Shift + B',
    "Pendenza": '⇧ Shift + N',
    "Intersezione": '⇧ Shift + M',
    "Punto su oggetto": `${getAltKeyStr()} + Q`,
    "Vincola / Svincola punto": `${getAltKeyStr()} + W`,
    "Estremo": `${getAltKeyStr()} + E`,
    "Radici": `${getAltKeyStr()} + R`,
    "Segmento - lunghezza fissa": `${getAltKeyStr()} + T`,
    "Semiretta": `${getAltKeyStr()} + Y`,
    "Vettore": `${getAltKeyStr()} + U`,
    "Vettore - dati un punto e la direzione": `${getAltKeyStr()} + I`,
    "Polare o diametro": `${getAltKeyStr()} + O`,
    "Spezzata aperta": `${getAltKeyStr()} + P`,
    "Retta di regressione": `${getAltKeyStr()} + A`,
    "Circonferenza - centro e raggio": `${getAltKeyStr()} + S`,
    "Compasso": `${getAltKeyStr()} + D`,
    "Semicirconferenza": `${getAltKeyStr()} + F`,
    "Settore circolare": `${getAltKeyStr()} + G`,
    "Arco di circonferenza": `${getAltKeyStr()} + H`,
    "Circonferenza - tre punti": `${getAltKeyStr()} + J`,
    "Settore circolare - tre punti": `${getAltKeyStr()} + K`,
    "Arco di circonferenza - tre punti": `${getAltKeyStr()} + L`,
    "Poligono regolare": `${getAltKeyStr()} + Z`,
    "Poligono vettore": `${getAltKeyStr()} + X`,
    "Poligono rigido": `${getAltKeyStr()} + C`,
    "Ellisse": `${getAltKeyStr()} + V`,
    "Conica - cinque punti": `${getAltKeyStr()} + B`,
    "Parabola": `${getAltKeyStr()} + N`,
    "Iperbole": `${getAltKeyStr()} + M`,
    "Traslazione": `${getAltKeyStr()} + ⇧ Shift + Q`,
    "Rotazione": `${getAltKeyStr()} + ⇧ Shift + W`,
    "Simmetria assiale": `${getAltKeyStr()} + ⇧ Shift + E`,
    "Simmetria centrale": `${getAltKeyStr()} + ⇧ Shift + R`,
    "Omotetia": `${getAltKeyStr()} + ⇧ Shift + T`,
    "Inversione circolare": `${getAltKeyStr()} + ⇧ Shift + Y`,
    "Immagine": `${getAltKeyStr()} + ⇧ Shift + U`,
    "Testo": `${getAltKeyStr()} + ⇧ Shift + I`,
    "Penna": `${getAltKeyStr()} + ⇧ Shift + O`,
    "Grafico a mano libera": `${getAltKeyStr()} + ⇧ Shift + P`,
    "Relazione": `${getAltKeyStr()} + ⇧ Shift + A`,
    "Pulsante": `${getAltKeyStr()} + ⇧ Shift + S`,
    "Casella di controllo": `${getAltKeyStr()} + ⇧ Shift + D`,
    "Campo di inserimento": `${getAltKeyStr()} + ⇧ Shift + F`,
  },
  en: {
    "Move": '⇧ Shift + Q',
    "Point": '⇧ Shift + W',
    "Segment": '⇧ Shift + E',
    "Line": '⇧ Shift + R',
    "Polygon": '⇧ Shift + T',
    "Circle - center and point": '⇧ Shift + Y',
    "Select objects": '⇧ Shift + U',
    "Show / Hide label": '⇧ Shift + I',
    "Show / Hide object": '⇧ Shift + O',
    "Delete": '⇧ Shift + P',
    "Move Graphics view": '⇧ Shift + A',
    "Copy visual style": '⇧ Shift + S',
    "Midpoint or center": '⇧ Shift + D',
    "Perpendicular line": '⇧ Shift + F',
    "Midline of a segment": '⇧ Shift + G',
    "Parallel line": '⇧ Shift + H',
    "Bisector": '⇧ Shift + J',
    "Tangents": '⇧ Shift + K',
    "Locus": '⇧ Shift + L',
    "Angle": '⇧ Shift + Z',
    "Angle with given size": '⇧ Shift + X',
    "Distance or length": '⇧ Shift + C',
    "Area": '⇧ Shift + V',
    "Slider": '⇧ Shift + B',
    "Slope": '⇧ Shift + N',
    "Intersection": '⇧ Shift + M',
    "Point on object": `${getAltKeyStr()} + Q`,
    "Fix / Unfix point": `${getAltKeyStr()} + W`,
    "Endpoint": `${getAltKeyStr()} + E`,
    "Roots": `${getAltKeyStr()} + R`,
    "Segment - fixed length": `${getAltKeyStr()} + T`,
    "Ray": `${getAltKeyStr()} + Y`,
    "Vector": `${getAltKeyStr()} + U`,
    "Vector - given a point and direction": `${getAltKeyStr()} + I`,
    "Polar or diameter": `${getAltKeyStr()} + O`,
    "Open polyline": `${getAltKeyStr()} + P`,
    "Regression line": `${getAltKeyStr()} + A`,
    "Circle - center and radius": `${getAltKeyStr()} + S`,
    "Compass": `${getAltKeyStr()} + D`,
    "Semicircle": `${getAltKeyStr()} + F`,
    "Circular sector": `${getAltKeyStr()} + G`,
    "Arc of a circle": `${getAltKeyStr()} + H`,
    "Circle - three points": `${getAltKeyStr()} + J`,
    "Circular sector - three points": `${getAltKeyStr()} + K`,
    "Arc of a circle - three points": `${getAltKeyStr()} + L`,
    "Regular polygon": `${getAltKeyStr()} + Z`,
    "Vector polygon": `${getAltKeyStr()} + X`,
    "Rigid polygon": `${getAltKeyStr()} + C`,
    "Ellipse": `${getAltKeyStr()} + V`,
    "Conic - five points": `${getAltKeyStr()} + B`,
    "Parabola": `${getAltKeyStr()} + N`,
    "Hyperbola": `${getAltKeyStr()} + M`,
    "Translation": `${getAltKeyStr()} + ⇧ Shift + Q`,
    "Rotation": `${getAltKeyStr()} + ⇧ Shift + W`,
    "Axial symmetry": `${getAltKeyStr()} + ⇧ Shift + E`,
    "Central symmetry": `${getAltKeyStr()} + ⇧ Shift + R`,
    "Dilation": `${getAltKeyStr()} + ⇧ Shift + T`,
    "Circular inversion": `${getAltKeyStr()} + ⇧ Shift + Y`,
    "Image": `${getAltKeyStr()} + ⇧ Shift + U`,
    "Text": `${getAltKeyStr()} + ⇧ Shift + I`,
    "Pen": `${getAltKeyStr()} + ⇧ Shift + O`,
    "Freehand graph": `${getAltKeyStr()} + ⇧ Shift + P`,
    "Relation": `${getAltKeyStr()} + ⇧ Shift + A`,
    "Button": `${getAltKeyStr()} + ⇧ Shift + S`,
    "Checkbox": `${getAltKeyStr()} + ⇧ Shift + D`,
    "Input box": `${getAltKeyStr()} + ⇧ Shift + F`,
  }
};

export default function getDefaultToolShortcuts() {
  const languageKey = getCurrentLanguage();
  return defaultShortcuts[languageKey];
}