import selectTool from "../functions/select-tool";
import {Tool} from "../functions/get-tool-map";
import {LOCAL_STORAGE_LANGUAGE_KEY} from "./local-storage-shortcuts-key";

const actions = {
  en: [
    "Move",
    "Point",
    "Segment",
    "Line",
    "Polygon",
    "Circle - center and point",
    "Select objects",
    "Show / Hide label",
    "Show / Hide object",
    "Delete",
    "Move Graphics view",
    "Copy visual style",
    "Midpoint or center",
    "Perpendicular line",
    "Midline of a segment",
    "Parallel line",
    "Bisector",
    "Tangents",
    "Locus",
    "Angle",
    "Angle with given size",
    "Distance or length",
    "Area",
    "Slider",
    "Slope",
    "Intersection",
    "Point on object",
    "Fix / Unfix point",
    "Endpoint",
    "Roots",
    "Segment - fixed length",
    "Ray",
    "Vector",
    "Vector - given a point and direction",
    "Polar or diameter",
    "Open polyline",
    "Regression line",
    "Circle - center and radius",
    "Compass",
    "Semicircle",
    "Circular sector",
    "Arc of a circle",
    "Circle - three points",
    "Circular sector - three points",
    "Arc of a circle - three points",
    "Regular polygon",
    "Vector polygon",
    "Rigid polygon",
    "Ellipse",
    "Conic - five points",
    "Parabola",
    "Hyperbola",
    "Translation",
    "Rotation",
    "Axial symmetry",
    "Central symmetry",
    "Dilation",
    "Circular inversion",
    "Image",
    "Text",
    "Pen",
    "Freehand graph",
    "Relation",
    "Button",
    "Checkbox",
    "Input field"
  ],
  it: [
    "Muovi",
    "Punto",
    "Segmento",
    "Retta",
    "Poligono",
    "Circonferenza - centro e punto",
    "Seleziona oggetti",
    "Mostra / Nascondi etichetta",
    "Mostra / Nascondi oggetto",
    "Elimina",
    "Muovi la vista Grafici",
    "Copia stile visuale",
    "Punto medio o centro",
    "Retta perpendicolare",
    "Asse di un segmento",
    "Retta parallela",
    "Bisettrice",
    "Tangenti",
    "Luogo",
    "Angolo",
    "Angolo di data misura",
    "Distanza o lunghezza",
    "Area",
    "Slider",
    "Pendenza",
    "Intersezione",
    "Punto su oggetto",
    "Vincola / Svincola punto",
    "Estremo",
    "Radici",
    "Segmento - lunghezza fissa",
    "Semiretta",
    "Vettore",
    "Vettore - dati un punto e la direzione",
    "Polare o diametro",
    "Spezzata aperta",
    "Retta di regressione",
    "Circonferenza - centro e raggio",
    "Compasso",
    "Semicirconferenza",
    "Settore circolare",
    "Arco di circonferenza",
    "Circonferenza - tre punti",
    "Settore circolare - tre punti",
    "Arco di circonferenza - tre punti",
    "Poligono regolare",
    "Poligono vettore",
    "Poligono rigido",
    "Ellisse",
    "Conica - cinque punti",
    "Parabola",
    "Iperbole",
    "Traslazione",
    "Rotazione",
    "Simmetria assiale",
    "Simmetria centrale",
    "Omotetia",
    "Inversione circolare",
    "Immagine",
    "Testo",
    "Penna",
    "Grafico a mano libera",
    "Relazione",
    "Pulsante",
    "Casella di controllo",
    "Campo di inserimento"
  ]
};

const languageKey = (localStorage.getItem(LOCAL_STORAGE_LANGUAGE_KEY) as "it" | "en") || "en"

const actionNames = (actions[languageKey] as Tool[]).reduce((acc, action) => ({
  ...acc,
  [action]: () => selectTool(action)
}), {} as Record<Tool, () => void>);

export default actionNames;