import {Tool} from "./tool-map";
import {getAltKeyStr} from "../functions/get-device-key-strings";

const defaultToolShortcuts: Record<Tool, string> = {
  "Muovi": '⇧ Shift + Q',
  "Punto": '⇧ Shift + W',
  "Segmento": '⇧ Shift + E',
  "Retta": '⇧ Shift + R',
  "Poligono": '⇧ Shift + T',
  "Circonferenza - centro e punto": '⇧ Shift + Y',
  "Seleziona oggetti": '⇧ Shift + U',
  "Mostra / Nascondi etichetta": '⇧ Shift + I',
  "Mostra / Nascondi oggetto": '⇧ Shift + O',
  "Elimina": '⇧ Shift + P',
  "Muovi la vista Grafici": '⇧ Shift + A',
  "Copia stile visuale": '⇧ Shift + S',
  "Punto medio o centro": '⇧ Shift + D',
  "Retta perpendicolare": '⇧ Shift + F',
  "Asse di un segmento": '⇧ Shift + G',
  "Retta parallela": '⇧ Shift + H',
  "Bisettrice": '⇧ Shift + J',
  "Tangenti": '⇧ Shift + K',
  "Luogo": '⇧ Shift + L',
  "Angolo": '⇧ Shift + Z',
  "Angolo di data misura": '⇧ Shift + X',
  "Distanza o lunghezza": '⇧ Shift + C',
  "Area": '⇧ Shift + V',
  "Slider": '⇧ Shift + B',
  "Pendenza": '⇧ Shift + N',
  "Intersezione": '⇧ Shift + M',
  "Punto su oggetto": `${getAltKeyStr()} + Q`,
  "Vincola / Svincola punto": `${getAltKeyStr()} + W`,
  "Estremo": `${getAltKeyStr()} + E`,
  "Radici": `${getAltKeyStr()} + R`,
  "Segmento - lunghezza fissa": `${getAltKeyStr()} + T`,
  "Semiretta": `${getAltKeyStr()} + Y`,
  "Vettore": `${getAltKeyStr()} + U`,
  "Vettore - dati un punto e la direzione": `${getAltKeyStr()} + I`,
  "Polare o diametro": `${getAltKeyStr()} + O`,
  "Spezzata aperta": `${getAltKeyStr()} + P`,
  "Retta di regressione": `${getAltKeyStr()} + A`,
  "Circonferenza - centro e raggio": `${getAltKeyStr()} + S`,
  "Compasso": `${getAltKeyStr()} + D`,
  "Semicirconferenza": `${getAltKeyStr()} + F`,
  "Settore circolare": `${getAltKeyStr()} + G`,
  "Arco di circonferenza": `${getAltKeyStr()} + H`,
  "Circonferenza - tre punti": `${getAltKeyStr()} + J`,
  "Settore circolare - tre punti": `${getAltKeyStr()} + K`,
  "Arco di circonferenza - tre punti": `${getAltKeyStr()} + L`,
  "Poligono regolare": `${getAltKeyStr()} + Z`,
  "Poligono vettore": `${getAltKeyStr()} + X`,
  "Poligono rigido": `${getAltKeyStr()} + C`,
  "Ellisse": `${getAltKeyStr()} + V`,
  "Conica - cinque punti": `${getAltKeyStr()} + B`,
  "Parabola": `${getAltKeyStr()} + N`,
  "Iperbole": `${getAltKeyStr()} + M`,
  "Traslazione": `${getAltKeyStr()} + ⇧ Shift + Q`,
  "Rotazione": `${getAltKeyStr()} + ⇧ Shift + W`,
  "Simmetria assiale": `${getAltKeyStr()} + ⇧ Shift + E`,
  "Simmetria centrale": `${getAltKeyStr()} + ⇧ Shift + R`,
  "Omotetia": `${getAltKeyStr()} + ⇧ Shift + T`,
  "Inversione circolare": `${getAltKeyStr()} + ⇧ Shift + Y`,
  "Immagine": `${getAltKeyStr()} + ⇧ Shift + U`,
  "Testo": `${getAltKeyStr()} + ⇧ Shift + I`,
  "Penna": `${getAltKeyStr()} + ⇧ Shift + O`,
  "Grafico a mano libera": `${getAltKeyStr()} + ⇧ Shift + P`,
  "Relazione": `${getAltKeyStr()} + ⇧ Shift + A`,
  "Pulsante": `${getAltKeyStr()} + ⇧ Shift + S`,
  "Casella di controllo": `${getAltKeyStr()} + ⇧ Shift + D`,
  "Campo di inserimento": `${getAltKeyStr()} + ⇧ Shift + F`,
};

export default defaultToolShortcuts;